
def test_fault():
    import fault
    print(fault)

